version: '3.9'
services:
  postrgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=FIAP-DELIVERY-ORDER
    ports:
      - "5432:5432"