name: CI

on:
  push:
    branches:
      - main
      - testes-unitarios
  pull_request:
    branches:
      - main
      - testes-unitarios

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Grant execute permission for gradlew 
        run: chmod +x ./gradlew
     
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Tests
        run: ./gradlew test 
       
      - name: Upload Test Results 
        uses: actions/upload-artifact@v4 
        with: 
          name: test-results 
          path: build/reports/tests/test
